#cuando se ejecute local usara el puerto 8080,
# pero cuando se suba a la nube, el servidor asignara un puerto dinamico
# ==========================================
# 1. SERVIDOR
# En la nube (Render), el puerto lo asigna el servidor dinámicamente.
# En local, seguirá usando el 8080.
server.port=${PORT:8080}
#necesario para que spring detecte correctamente el puerto asignado por el servidor en la nube
server.forward-headers-strategy=framework
spring.application.name=portafolioBackend

# ==========================================
# 2. BASE DE DATOS (Nativa de la Nube)
# Usamos variables de entorno. Lo que está después de los ':' es el valor para tu PC local.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portafolio_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# ==========================================
# 3. HIBERNATE (ORM)
# En producción NUNCA se usa 'update' porque podría corromper datos reales.
# Lo pasaremos por variable de entorno para que sea 'update' en local y 'none' o 'validate' en la nube.
spring.jpa.hibernate.ddl-auto=${DB_DDL:update}
spring.jpa.show-sql=true
#ayudamos a hibernate a saber que tipo de base de datos estamos usando, para que pueda generar el SQL correcto
#es opcional, pero recomendado. Si no se pone, hibernate lo detecta automáticamente.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# 4. LÍMITES DE SUBIDA (Para Cloudinary)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ==========================================
# 5. SWAGGER / OPENAPI (Documentación) uso variables de entorno para que en local se pueda ver la documentación y en producción no.
# Usamos las rutas por defecto de springdoc:
#  - OpenAPI JSON -> /v3/api-docs
#  - Swagger UI -> /swagger-ui.html y /swagger-ui/index.html
# Ordenar la interfaz visual
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
#  Ocultar la barra verde superior de "Explore"
springdoc.swagger-ui.layout=BaseLayout
# Evitar que Swagger busque configuraciones raras por defecto
springdoc.swagger-ui.disable-swagger-default-url=true