#cuando se ejecute local usara el puerto 8080,
# pero cuando se suba a la nube, el servidor asignara un puerto dinamico
# ==========================================
# 1. SERVIDOR
# En la nube (Render), el puerto lo asigna el servidor dinámicamente.
# En local, seguirá usando el 8080.
server.port=${PORT:8080}
spring.application.name=portafolioBackend

# ==========================================
# 2. BASE DE DATOS (Nativa de la Nube)
# Usamos variables de entorno. Lo que está después de los ':' es el valor para tu PC local.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portafolio_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# ==========================================
# 3. HIBERNATE (ORM)
# En producción NUNCA se usa 'update' porque podría corromper datos reales.
# Lo pasaremos por variable de entorno para que sea 'update' en local y 'none' o 'validate' en la nube.
spring.jpa.hibernate.ddl-auto=${DB_DDL:update}
spring.jpa.show-sql=true

# ==========================================
# 4. LÍMITES DE SUBIDA (Para Cloudinary)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB